blog/urls.py
from django.urls import path
from .views import (PostListView, 
                    # PostDetailView, 
                    PostCreateView, 
                    PostUpdateView, 
                    PostDeleteView,
                    UserPostListView,
                    )
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('<slug:slug>/',views.details, name='post-detail'),
    path('<slug:slug>/share',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',PostListView.as_view(), name='post-list-by-tag'),
    # path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='post-update'),  
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # path('category/<slug:slug>/', views.post_category, name='post_category'),
]

jasminesite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from taggit.managers import TaggableManager



# Create your models here.
class PostCategory(models.Model):
    cat_title       = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(blank=True)
    cat_desc        = models.TextField()

    class Meta:
        verbose_name = 'postcategory'
        verbose_name_plural = 'postcategories'

    def __str__(self):
        return self.cat_title

    def get_absolute_url(self):
        return reverse('blog:category.html', args=[self.slug])


class Post(models.Model):
    title           = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(null=True)
    content         = models.TextField()
    date_posted     = models.DateTimeField(default=timezone.now)
    thumb           = models.ImageField(blank=True, null=True, upload_to='images/')
    author          = models.ForeignKey(User, on_delete=models.CASCADE)
    featured        = models.BooleanField(default=False)
    published       = models.BooleanField(default=False)
    category        = models.ForeignKey(PostCategory, null=True, on_delete=models.CASCADE)

    tags = TaggableManager()

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[0:120] + '...'

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})



class Comment(models.Model):
    post                = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name                = models.CharField(max_length=50)
    email               = models.EmailField()
    body                = models.TextField()
    date                = models.DateTimeField(default=timezone.now)
    active              = models.BooleanField(default=True)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug

blog/forms.py
from django import forms
from .models import Post, Comment


class PostEmailForm(forms.Form):
    name    = forms.CharField(max_length=100)
    email   = forms.EmailField()
    to      = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'thumb',
            'category',
        ]

class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'name',
            'email',
            'body',    
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from .models import Post, PostCategory, Comment
from .forms import PostModelForm, PostCommentForm, PostEmailForm
from taggit.models import Tag
from django.db.models import Count

# Create your views here.
def post_share(request, slug):
    post        = get_object_or_404(Post, slug=slug, published=True)
    sent        = False

    if request.method == 'POST':
        form    = PostEmailForm(request.POST)
        if form.is_valid():
            cd          = form.cleaned_data
            post_url    = request.build_absolute_uri(post.get_absolute_url())
            subject     = '{} ({}) recommends you read "{}"'.format(cd['name'], cd['email'], post.title)
            message     = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comment'])
            send_mail(subject, message, 'neupytechng@gmail.com', [cd['to']])
            sent        = True
    else:
        form    = PostEmailForm()
    context = {
        'form':form,
        'post':post,
        'sent':sent
    }
    return render(request, 'blog/share.html', context)

class PostListView(ListView):
    tag_slug=None
    tag=None
    category_slug=None
    if tag_slug:
        tag             = get_object_or_404(Tag, slug=tag_slug)
        object_list     = object_list.filter(tags__in=[tag])
    model = Post
    queryset = Post.objects.filter(published=True)
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 20

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_post.html'
    context_object_name = 'posts'
    paginate_by = 20

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


def details(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = PostCommentForm(data=request.POST)
        if comment_form.is_valid():
            new_commment = comment_form.save(commit=False)
            new_commment.post = post
            new_commment.save()

    else:
        comment_form = PostCommentForm
    posts_tags_ids      = post.tags.values_list('id', flat=True)
    similar_posts       = Post.objects.filter(tags__in=posts_tags_ids).exclude(id=post.id)
    similar_posts       = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published')[:4]
    
    context = {
        'title': 'Blog Details',
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'similar_posts': similar_posts
        }
    return render(request, 'blog/post_detail.html', context)

class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'blog/post_create.html'
    form_class = PostModelForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    template_name = 'blog/post_create.html'
    queryset = Post.objects.all()
    form_class = PostModelForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_success_url(self):
        return reverse('blog:blog-home')

blog/templates/blog/home.html
{% extends 'layout.html' %}

{% block content %}

<div id="blog" class="container">
    <div class="row">
        {% for post in posts %}
        <div id="blog-post" class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'blog:post-detail' post.slug %}">
                        <img src="{{ post.thumb.url }}" alt="">
                    </a> 
                </div>
                <div id="blog-info" class="col-md-6">
                    <h2><a href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a></h2>
                    <small><i class="far fa-clock mr-2"></i> {{ post.date_posted|date:"F d, Y" }}</small>
                    <p><i class="far fa-user mr-2"></i><a href="{% url 'user-post' post.author.username %}">{{ post.author|capfirst }}</a></p>
                    <i class="fas fa-tags"></i>
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post-list-by-tag' tag.slug %}">
                    {{ tag.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    <p>{{ post.snippet|safe }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
            {% if is_paginated %}
            <nav aria-label="Page navigation example my-4">
                <ul class="pagination">
                {% if page_ogj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&laquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="pag-item active">
                        <a class="page-link">{{ num }}<span class="sr-only">(current)</span></a>
                    </li>
                    {% else %}
                    <li class="pag-item active">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                    {% endif %}
                {% endfor %}

                {% if page_ogj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/post_cat.html
{% extends 'layout.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">         
            {% for post in posts %}
            <a href="{% url 'blog:post-detail' post.slug %}">
                <img src="{{ post.thumb.url }}" alt="Image" class="img-responsive">
                <h1>{{ post.title }}</h1>
                <p>{{ post.content }}</p>
            </a>
                <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                <h5><a href="{% url 'user-post' post.author.username %}">{{ post.author|capfirst }}</a></h5>
                <div>
                    <i class="fab fa-facebook-square"></i>
                    <i class="fab fa-twitter"></i>
                </div>
            {% endfor %}

<!-- Pagination -->
        <div class="my-4">
            {% if is_paginated %}
            <nav aria-label="Page navigation example my-4">
                <ul class="pagination">
                {% if page_ogj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&laquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="pag-item active">
                        <a class="page-link">{{ num }}<span class="sr-only">(current)</span></a>
                    </li>
                    {% else %}
                    <li class="pag-item active">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                    {% endif %}
                {% endfor %}

                {% if page_ogj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
<!-- End Pagination -->

        </div>
        <div class="col-md-4">
            <h3 class="text-muted">Trending Tweets</h3>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'layout.html' %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="POST" action="">{% csrf_token %}
                <fieldset class="form-group">
                    <legend class="mb-4">New Post</legend>
                    <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
                </fieldset>
                <div>
                    <button class="mb-3 btn btn-outline-danger" type="submit">Yes, delete</a></button>
                    <button class="mb-3 btn btn-outline-info"><a href="{% url 'blog:post-detail' post.slug %}">Cancel</a></button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
                <fieldset class="form-group">
                    <legend class="mb-4">New Post</legend>
                    {{ form.media}}
                    {{ form|crispy}}
                </fieldset>
                <button class="mb-3 btn btn-outline-info" type="submit">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container bg-light ">
    <div id="blog-details">
        <div class="row">
            <h1 class="mx-auto display-3">{{ post.title }}</h1>
        </div>
        <div class="row">
                <ul class="blog-nav mx-auto">
                    <li><i class="far fa-user mr-2"></i><a href="{% url 'user-post' post.author.username %}">{{ post.author|capfirst }}</a></li>
                    <li>
                        <i class="far fa-calendar-alt mr-2"></i>{{ post.date_posted|date:"F d, Y" }}
                    </li>
                    <li>
                        {% with comments.count as total_comments %}<i class="far fa-comments mr-2"></i>
                        {{ total_comments }} Comment{{ total_comments|pluralize }}
                        {% endwith %}
                    </li>
                </ul>
            </div>
        
            <div class="row">
                <img class="mx-auto" src="{{ post.thumb.url }}" alt="">
            </div> 
            <div class="row">
                <p>{{ post.content|safe }}</p>
            </div>
            <div class="row">
                <h5>Share this post</h5>
                <div>
                    <div id="fb-root"></div>
                <script>(function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;
                    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
                </script>
                    <!-- Your share button code -->
                    <ul id="share-icons">
                        <li>
                            <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true">
                            </div>
                        </li>
                        <li>
                            <a href="{{ request.build_absolute_uri }}" class="twitter-share-button" data-show-count="true">Tweet</a>
                        </li>
                        <li>
                           <a href="{% url 'blog:post_share' post.slug %}"><i class="far fa-envelope fa-2x"></i></a> 
                        </li>
                    </ul>
                    
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
            </div>
    </div>
</div>


<div class="container bg-light">
    <section id="comment">
        <div class="row">
            <div>
                <div>
                    {% with comments.count as total_comments %}
                    <h3>{{ total_comments }} Comment{{ total_comments|pluralize }}</h3>
                    {% endwith %}
    
                    {% for comment in comments %}
                    <div>
                        <p>Comment {{ forloop.counter }} by {{ comment.name.capitalize }} {{ comment.date }} {{ comment.body|linebreaks }}</p>
                    </div>
                    {% empty %}
                    <p>Be the first to comment</p>
                    {% endfor %}
    
                    {% if new_comment %}
                    <h3>Your comment has been added</h3>
                    {% else %}
                    <h3>Add a new comment</h3>
                    <form method="POST" action="">{% csrf_token %}
                        {{ comment_form|crispy }}
                        <input class="btn btn-primary" type="submit" value="Add comment">
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row p-4">
            {% for post in similar_posts %}
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            {% empty %}
            There are no similar posts
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

blog/templates/blog/share.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div id="share" class="container">
    {% if sent %}
    <div class="bg-success">
        <h2>{{ post.title }} was successfully sent by email</h2>
    </div>
    {% else %}
    <h2>Share "{{ post.title }}" by email</h2>
    <form action="" method="POST">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Share Post">
    </form>
    {% endif %}
</div>

{% endblock %}

blog/templates/blog/user_post.html
{% extends 'layout.html' %}


{% block content %}
<div id="blog" class="container">
        <h1>Posts By {{ view.kwargs.username|capfirst }}</h1>
        <div class="row">
            {% for post in posts %}
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6 img">
                        <a href="{% url 'blog:post-detail' post.slug %}">
                            <img src="{{ post.thumb.url }}" alt="">
                        </a> 
                    </div>
                    <div id="blog-info" class="col-md-6">
                        <h2>{{ post.title }}</h2>
                        <small><i class="far fa-clock mr-2"></i> {{ post.date_posted|date:"F d, Y" }}</small>
                        <p><i class="far fa-user mr-2"></i><a href="{% url 'user-post' post.author.username %}">{{ post.author|capfirst }}</a></p>
                        <i class="fas fa-tags"></i>
                        {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post-list-by-tag' tag.slug %}">
                        {{ tag.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </div>
                    </div>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            {% if is_paginated %}
                <nav aria-label="Page navigation example my-4">
                    <ul class="pagination">
                    {% if page_ogj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                    </li>
                    {% endif %}
    
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                        <li class="pag-item active">
                            <a class="page-link">{{ num }}<span class="sr-only">(current)</span></a>
                        </li>
                        {% else %}
                        <li class="pag-item active">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
    
                    {% if page_ogj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                    {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>

{% endblock %}