blog/urls.py
from django.urls import path
from .views import (PostListView, 
                    # PostDetailView, 
                    PostCreateView, 
                    PostUpdateView, 
                    PostDeleteView,
                    UserPostListView,
                    )
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('<slug:slug>/',views.details, name='post-detail'),
    path('<slug:slug>/share',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',PostListView.as_view(), name='post-list-by-tag'),
    # path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='post-update'),  
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # path('category/<slug:slug>/', views.post_category, name='post_category'),
]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('', views.contactView, name='contact'),
    path('success', views.successView, name='success'),
]

jasminesite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
]

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>JasmineCakes</title>
</head>
<body>
    
    <nav class="container nav-wrapper navbar-fixed">
        <div class="container">
            <div class="nav-wrapper">
                <a href="{% url 'pages:home' %}" class="brand-logo">JasmineCakes</a>
                <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'pages:about' %}">About Us</a></li>
                <li><a href="{% url 'pages:gallery' %}">Gallery</a></li>
                <li><a href="{% url 'contact:contact' %}">Contact Us</a></li>
                <li><a href="{% url 'blog:blog-home' %}">Blog</a></li>
                </ul>
            </div>
        </div>
    </nav>
            
    <ul class="sidenav peach lighten-3" id="mobile-nav">
        <li><a href="{% url 'pages:about' %}">About Us</a></li>
        <li><a href="{% url 'pages:gallery' %}">Gallery</a></li>
        <li><a href="{% url 'contact:contact' %}">Contact Us</a></li>
        <li><a href="{% url 'blog:blog-home' %}">Blog</a></li>
    </ul> 

    <!-- Django Template Tags -->
    <div class="container purple lighten-4 z-depth-5">
      {% block content %}
      {% endblock %}
      <footer class="page-footer">
              <div class="container">
                <div class="row">
                  <div class="address col m6 s12">
                    <h5 class="white-text">Come visit us!</h5>
                    <p class="grey-text text-lighten-4">14, Ring Road, Idua Eket, Akwa Ibom State</p>
                    <p><i class="fas fa-phone"></i> +234 7080230375</p>
                  </div>
                  <div class="social col m6 s12">
                    <h5 class="white-text">Follow Us on social!</h5>
                    <a href=""><i class="fab fa-twitter"></i></a>
                    <a href=""><i class="fab fa-facebook"></i></a>
                    <a href=""><i class="fab fa-instagram"></i></a>                   
                    <ul>
                      <li><a class="grey-text text-lighten-3" href="{% url 'pages:about' %}">About Us</a></li>
                      <li><a class="grey-text text-lighten-3" href="{% url 'pages:gallery' %}">Gallery</a></li>
                      <li><a class="grey-text text-lighten-3" href="{% url 'contact:contact' %}">Contact Us</a></li>
                      <li><a class="grey-text text-lighten-3" href="{% url 'blog:blog-home' %}">Blog</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="footer-copyright center">
                <div class="container">
                &copy; {% now 'Y' %} Jasmine Cakes and Chops Co.| <a href="">Policy</a>
                </div>
              </div>
            </footer>
          
    </div>
    
    <script src="{% static 'js/materialize.min.js' %}"></script>

    <!-- Mobile Navbar -->
    <script>
       const sideNav = document.querySelector('.sidenav');
       M.Sidenav.init(sideNav, {});   
       
       const slider = document.querySelectorAll('.slider');
       M.Slider.init(slider, {
           indicators: false,
           height: 500
        });

        const gal = document.querySelectorAll('.materialboxed');
        M.Materialbox.init(gal, {});

        const elems = document.querySelectorAll('.datepicker');
        M.Datepicker.init(elems, {
          format: 'yyyy-mm-dd'
        });
    </script>    
</body>
</html>